INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(1,'It\'s a Teethday Party! (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(1,'An OrganWise Fieldtrip (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(1,'Counting on You to Play (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(1,'Keeping your "Pets" Healthy (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(1,'Feed Your OrganWise "Pets" (game) ',30,5,1,0,0,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(2,'Cheering for Healthy Choices (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(2,'Click on your Sir Rebrum (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(2,'FIBER-ific Fashion (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(2,'What\'s on your Plate? (book/oral lesson) ',30,5,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(2,'FIBER-ific Fashions (game) ',30,5,1,0,0,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(3,'School Days Here We Come (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(3,'I Think I Forgot Something (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(3,'All Hearts Need Love (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(3,'Taking a Healthy Break (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(3,'Here We Are! (puzzle) ',15,5,1,1,1,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(4,'My Favorite Drink in the World (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(4,'Bone Bank Savings (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(4,'A Teeth Changing Experience (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(4,'An Active Bone Life ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(4,'Calci\'s Bone Bank (game) ',30,5,1,1,1,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(5,'Clean Air March (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(5,'A Healthy Victory (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(5,'Five a Day Reporter (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(5,'A No Smoking Policy (book/oral lesson) ',30,5,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(5,'Windy\'s No Smoking (card game) ',30,5,1,1,1,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(6,'Are you GermWise? (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(6,'Food Safety 101 (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(6,'Making OrganWise Choices (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(6,'Concentration on Fruits & Veggies (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(6,'Concentrating on Smart Choice (game) ',30,5,1,2,2,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(7,'Poetry in Motion (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(7,'A Family Meal Plan (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(7,'An Active Role Model (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(7,'MyPyramid Activities (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(7,'MyPyramid (activity/puzzle) ',15,5,1,2,2,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(8,'Ideas for a Healthier World (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(8,'MyPyramid Project (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(8,'A High-Fiber Movement (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(8,'Water Lessons from a Kid (book/oral lesson) ',30,5,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(8,'Concentrating on MyPyramid (game) ',30,5,1,2,2,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'The Healthy Heart Challenge (book/oral lesson) ',30,2,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'How to be Smart From The Inside Out (book/oral lesson) ',30,2,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Basic Training for Better Health (book/oral lesson) ',30,2,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Train Your Brain (book/oral lesson) ',30,2,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Balancing The Energy Equation (book/oral lesson) ',30,2,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Pepto\'s Place (book/oral lesson) ',30,2,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'How to be Smart From The Inside Out (book/oral lesson) ',30,2,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Basic Training for Better Health (book/oral lesson) ',30,2,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Train Your Brain (book/oral lesson) ',30,2,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Balancing The Energy Equation (book/oral lesson) ',30,2,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Undercover Diabetes Health Agents (book/oral lesson) ',30,2,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'How to be Smart From The Inside Out (book/oral lesson) ',30,2,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Basic Training for Better Health (book/oral lesson) ',30,2,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Train Your Brain (book/oral lesson) ',30,2,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(9,'Balancing The Energy Equation (book/oral lesson) ',30,2,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Gimme Five DVD',15,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Gimme Five Activity Sheet ',15,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Breakfast Skippin\' Blues DVD',15,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Breakfast Skippin\' Blues Activity Sheet ',15,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Calci\'s Big Race DVD',15,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Calci\'s Big Race Activity Sheet ',15,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Extreme Couch Potato DVD',15,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Extreme Couch Potato Activity Sheet ',15,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Fiber Fandango DVD',15,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Fiber Fandango Activity Sheet ',15,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'H2Ohhhhh! DVD',15,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'H2Ohhhhh! Activity Sheet ',15,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Farmer’s Market Fresh DVD',15,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Farmer\'s Market Fresh Activity Sheet ',15,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Pepto’s Party Portions DVD',15,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Pepto\'s Party Portions Activity Sheet ',15,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'Keepin\' the Beat Music CD (# of songs played) ',2,16,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(10,'The OrganWise Guys Shorts DVD (# of shorts played) ',1,72,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Desktop Stretching  ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Air Step Aerobics ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Pretend Rope Jumping ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Chair Aerobics ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Canned Food ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'Mind in Motion ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'DVD Worksheet - Desktop Stretching',30,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'DVD Worksheet - Air Step Aerobics',30,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'DVD Worksheet - Pretend Rope Jumping',30,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'DVD Worksheet - Chair Aerobics ',30,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(11,'DVD Worksheet - Canned Food',30,1,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 1.1 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 1.2 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 2.1 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 2.2 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 3.1 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 3.2 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 4.1 ',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'Level 4.2',5,10,0,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(12,'My Mind in Motion Sequence Handout',30,10,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 1.1 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 1.2 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 2.1 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 2.2 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 3.1 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 3.2 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 4.1 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Level 4.2 ',5,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'Create Your Own Routine Handout',30,10,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(13,'My Routine Handout',30,10,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Cheering for Healthy Choices-Capitalization & Punctuation ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'What\'s on your Plate-Alphabetizing ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'What\'s on your Plate-Writing ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'FIBER-ific Fashion!-Graphing ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Gimme Five-Patterns ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'It\'s a Teethday Party-Sequencing ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Vegetable Stand-Money ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'What\'s on your Plate?-Adding and Subtracting ',45,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Hardy Heart, I Think I Forgot Something-Writing ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Hardy Heart, School Days Here We Come!-Cause and Effect ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Hardy Heart, School Days Here We Come!-Comprehension ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Hardy Heart, School Days Here We Come!-3 Part Comprehension ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Windy The Lungs, Clean Air March-Writing ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Calci M. Bone, An Active Life-Positional Words ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Physical Figures  - Math',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Active Sight Words ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Daily Oral Language with Physical Activity Theme Daily ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Patterns With Physical Activity ',45,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Basic Training-Dictionary Skills ',45,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Ideas for a Healthier World-Letter Writing ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'A Family Meal Plan-Sequencing ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Food Stafety-Interpreting Illustrations ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Poetry in Motion-Poetry ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'How to be Smart from the Inside Out-Writing ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Water lessons from a Kid-Graphing ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Healthy Food Items-Money ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Making Predictions ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Graphing Go and Slow Activities ',45,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Fact & Opinion: Physical Activity Theme ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Persuasive Writing & Idioms ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Healthy Heart Challenge-Research Paper ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'How to be Smart from the Inside Out-Writing ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Train Your Brain-Story Pyramid ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Multiplication Story Problems ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Healthy Heart Challenge-Graphing ',45,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Types of Sentences ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Organ Annie/Andy-Persuasive Writing ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Pepto\'s Place-Cause and Effect ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Pepto\'s Place-Sentence Writing ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Smart from the Inside Out-Finding the Facts ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'An Active Role Model-Math ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Fun With Food Labels ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Pepto\'s Place-Graphing ',45,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Basic Training-Cause and Effect ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Basic Training-Poetry ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Undercover Diabetes Informational Writing ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Undercover Diabetes Main Idea Writing ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Basic Training Fractions ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Basic Training Graphing ',45,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(14,'Uncovering Diabetes-Line Graph ',45,1,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Apples ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Bell Peppers',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Blueberries ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Broccoli',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Carrots ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Cauliflower ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Cherry Tomatoes',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Cucumbers',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Grapes ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Kale',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Parsnips ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Peaches ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Snap Peas ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Spinach',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Strawberries ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Sweet Potatoes ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Turnips ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Winter Squash ',30,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(15,'Zucchini ',30,1,1,0,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #1 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #2 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #3 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #4 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #5 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #6 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #7 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #8 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #9 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #10 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #11 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #12 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #13 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #14 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #15 ',15,1,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #1 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #2 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #3 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #4 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #5 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #6 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #7 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #8 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #9 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #10 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #11 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #12 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #13 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #14 ',15,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(16,'Companion Activity page #15 ',15,1,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3 & 4 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 6 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,0,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 4',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 & 6 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,0,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3 & 4 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 & 6 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,0,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 4',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 & 6 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3 & 4 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 & 6 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 1 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 2 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 3 & 4 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 5 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 6 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 7 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 8 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 9 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 10 ',30,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(17,'Companion Activity page # 11 ',30,1,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,1,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,2,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Assembly Review Questions',10,1,1,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Body Walk Review Questions',10,1,1,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(18,'Body Walk Review Questions',10,1,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(19,'Family Food Fun Pack Demonstration ',60,1,0,3,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(19,'Family Fitness Fun Pack Demonstration ',60,1,1,3,4,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Survival Guide ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Arizona ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'California ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Hawaii ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Washington ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Wisconsin ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Michigan ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'North Carolina ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Georgia ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Pennsylvania ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Florida ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Your Turn Activity ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Check Your Learning ',25,1,1,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(20,'Reflection ',25,1,1,4,4,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 1 & 2 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 3 & 4 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 5 & 6 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 7 & 8 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 9 & 10 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 11 & 12 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 13 & 14 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 15 & 16 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 17 & 18 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 19 & 20 ',15,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Reflections ',20,1,0,3,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 1 & 2 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 3 & 4 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 5 & 6 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 7 & 8 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 9 & 10 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 11 & 12 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 13 & 14 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 15 & 16 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 17 & 18 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 19 & 20 ',15,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Reflections ',20,1,0,4,4,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 1 & 2 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 3 & 4 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 5 & 6 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 7 & 8 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 9 & 10 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 11 & 12 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 13 & 14 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 15 & 16 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 17 & 18 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Tracking & Graphing Math Problems 19 - 22 ',15,1,0,5,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(21,'Reflections ',20,1,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Steps 1 & 2',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 3',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 4',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 5',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 6',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 7',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 8',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 9',30,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(22,'Step 10',30,1,1,4,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(23,'Take Charge of Your Health ',60,1,1,5,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(24,'Nutrition/ Physical Activity Behavior Education Review ',15,1,1,0,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Healthy Eating Requires 5 Fruits and Vegetables Daily',25,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Family Fun Physical Activity',25,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Dairy Calcium Rich Foods and Why',25,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Choose Low-Fat Options',25,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Fruits and Vegetables-Good for You!',25,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Get Moving as a Family',25,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Having a Calcium Rich Diet',25,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Less Fat + A Healthier You!',25,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'A Colorful Plate',25,1,1,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Physical Activity for Families',25,1,1,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Increasing Calcium Intake',25,1,1,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Limiting Fat In Your Diet',25,1,1,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'High Fiber Foods',25,1,1,0,1,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Eat More Fiber',25,1,1,2,3,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Yay for High Fiber',25,1,1,4,5,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Reducing Screen Time',25,1,1,0,1,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Screen Time\'s Toll on Children',25,1,1,2,3,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(25,'Weighing In On Screen Time',25,1,1,4,5,0);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Focus on Fruits',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Be a Healthy Role Model for Children',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Choose My Plate',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Add More Vegetables To Your Day',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Eating Better On a Budget',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Build a Healthy Meal',10,1,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Make Half of Your Grains Whole',10,1,1,0,5,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Salt and Sodium',10,1,1,0,5,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Cut Back On Your Kids\' Sweet Treats',10,1,1,0,5,0);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(26,'Smart Shopping For Veggies and Fruits',10,1,1,0,5,0);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(27,'Kid2Kid Newsletter Vol. 5 No. 1',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(27,'Kid2Kid Newsletter Vol. 5 No. 2',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(27,'Kid2Kid Newsletter Vol. 5 No. 3',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(27,'Kid2Kid Newsletter Vol. 5 No. 4',45,1,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'August',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'September',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'October',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'November',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'December',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'January',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'February',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'March',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'April',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'May',.25,20,1,0,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(28,'June',.25,20,1,0,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Warm up:  Cadence March',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Karate Kid Math',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Imaginary Jump Rope',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  OrganWise Story Problems',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Math in a Flash',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Math Jeopardy',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Sky Writing Math',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Money Bags',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Madame Muscle\'s Math Boot Camp',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Spelling OrganWise Style',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Jumping for Joy over Healthy Sentences',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Reading Cheerleading',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  OrganWise Story Telling',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Air Brush Writing',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Reading on the Move',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Taking a Phonics "Brake"',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  "I Spy" Phonics',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  A Shopping We Will Go',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Windy\'s Magical Garden',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Nutrition Through the Grapevine',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  OrganWise Snack Packing',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Hoe, Hoe, Hoe Your Garden',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Moving to MyPyramid',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Healthy and Proud',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Are You OrganWise?',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Cool Down:  Stretching/Breathing',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Cool Down:  Train Your Brain for Success',10,2,0,0,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Warm up:  Cadence March',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Karate Kid Math',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Imaginary Jump Rope',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  OrganWise Story Problems',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Math in a Flash',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Math Jeopardy',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Real World Math',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Money Bags',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Math:  Madame Muscle\'s Math Boot Camp',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Spelling OrganWise Style',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Pumped Up over Healthy Sentences',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Grammar Cheerleading',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Vocabulary….Football-Style',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Healthy Sentence Structure',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Reading Comprehension on the Move',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  Taking a Grammar "Brake"',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Language Arts:  A Class in Training',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Zero in on Nutrition Facts',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Windy\'s Magical Garden',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Nutrition Through the Grapevine',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  OrganWise Snack Packing',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  20 Questions for Health',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Moving to MyPyramid',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Healthy and Proud',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Nutrition/Health:  Are You OrganWise?',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Cool Down:  Stretching/Breathing',10,2,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(29,'Cool Down:  Train Your Brain for Success',10,2,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.1',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.2',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.3',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.4',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.5',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.6',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'K.7',20,2,1,0,0,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.1',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.2',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.3',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.4',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.5',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.6',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.7',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.8',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.9',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.10',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.11',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'1-2.12',20,2,1,1,2,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 1',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 2',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 3',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 4',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 5',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 6',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 7',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 8',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 9',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Persuasive 10',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 1',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 2',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 3',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 4',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 5',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 6',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Informational 7',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 1',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 2',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 3',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 4',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 5',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Narrative 6',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Response 1',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Response 2',45,2,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(30,'3-5 Response 3',45,2,1,3,5,1);

INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 1 No. 1',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 1 No. 2',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 1 No. 3',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 1',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 2',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 3',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 4',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 5',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 2 No. 6',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 3 No. 1',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 3 No. 2',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 3 No. 3',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 3 No. 4',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 3 No. 5',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 4 No. 1',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 4 No. 2',45,1,1,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'Kid2Kid Newsletter Vol. 4 No. 3',45,1,0,3,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Basic Training for Better Health',45,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Colorful Plates',45,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Are You Fruit and Veggie Wise?',45,1,0,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  A Fun Filled OrganWise Day',45,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Jump Start',45,1,0,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Look at Me Being Active',45,1,0,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  OrganWise Guys - Happy Hardy',45,1,1,0,1,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Are You Bone Wise?',45,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Are you "My Plate" Wise?',45,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  My Plate Possibilities',45,1,0,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Muscle, Heart and Brain Gyms',45,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Sensible Snacking',45,1,1,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  How to be Smart From the Inside Out',45,1,0,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  The Healthy Heart Challenge',45,1,0,2,3,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Being Physically Active',45,1,1,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Find the Fat',45,1,0,4,5,1);
INSERT INTO refResources (categoryId,title, minutesPerUse,maximumUsesPerMonth,nutrition,minGrade,maxGrade,enabled) VALUES(31,'HMP Supplemental Lesson:  Reducing Screen Time',45,1,1,4,5,1);
